program ::= declaration* EOF ;

declaration ::= filter_decl
                | statement ;

filter_decl ::= "@def" identifier ":"  expression ";"
statement ::= "@run" expression ("->" identifier | string)? ";"

expression ::= term (("||" term)*)

term ::= factor (("&&" factor)*)

factor ::=  "filme" "(" method_pattern ")"
          | "filinp" "(" declaring_type_pattern ")"
          | "filanno" "(" annotation_pattern ")"
          |  identifier
          | "(" expression ")"
          | "!" factor

method_pattern ::= modifier_pattern? ret_type (declaring_type_pattern ".")? name_pattern "(" param_pattern? ")" throws_pattern?
modifier_pattern ::= "public" | "protected" | "private"
ret_type ::= "*" | qualified_name
declaring_type_pattern ::= identifier ( ("."|"..") (identifier|"*"))*
name_pattern ::= "*" | regex_identifier | identifier
param_pattern ::= type_pattern_list | ".."
throws_pattern ::= "throws"  qualified_name ("," qualified_name)*

type_pattern_list ::= qualified_name ("," qualified_name)*
annotation_pattern ::= qualified_name
qualified_name ::= identifier ("." identifier)*

regex_identifier ::= "[a-zA-Z_*][a-zA-Z0-9_*]*"
identifier ::= "[a-zA-Z_][a-zA-Z0-9_]*"
string ::= ".*"
